// Generates src/demo.js by running the REAL engine over a synthetic wallet.
// The demo can therefore never drift from the engine's actual output shape.
// Run: node scripts/gen-demo.mjs
import { writeFileSync } from 'node:fs'
import { analyze } from '../api/_lib/engine.js'
import { makeWallet, makeRotationChain, DEFAULTS } from '../tests/synth.js'

// A wallet with a real leak AND real habits worth naming: the interesting case,
// not the strawman. Positive-payoff picks undone by tilt, escalation and toll.
// Trade count and return dispersion are set so the leak is actually PROVABLE —
// an earlier draft used 74 high-variance trades and the expectancy interval
// straddled zero, so the engine correctly refused to call it negative. If the
// demo is going to show a verdict, the verdict has to clear the same statistical
// bar a real wallet must clear.
const { txs } = makeWallet({
  nTrades: 128,
  winRate: 0.31,
  winRet: 1.62,
  lossRet: 0.56,
  retJitter: 0.09,
  holdWinMin: 11,
  holdLossMin: 310,
  holdJitter: 0.35,
  buySize: 0.85,
  buySizeCV: 0.5,
  gapAfterLossMin: 7,
  gapAfterWinMin: 95,
  revengeSizeMult: 2.1,
  interfaceFeeRate: 0.009,
  networkFee: 0.00015,
  openBags: 7,
  openBagSize: 1.3,
  seed: 20260727,
})

// The demo exercises the MARKED path, including its ugly edges — one bag that has
// moved up, several down, one with no tradable pool, one so large relative to pool
// depth that its mark is fiction. A demo that only shows the happy case would
// misrepresent what the feature actually does.
// Splice in rotation chains of both shapes, so the demo shows the rotation
// accounting rather than only describing it: two routed through SOL (valued
// exactly) and two direct pool swaps (basis carried forward).
const rotationTxs = [
  ...makeRotationChain({ routed: true, buySol: 1.2, rotateSol: 2.1, sellSol: 1.4, tag: 'd1',
    startTs: DEFAULTS.startTs + 86400 * 2 }).txs,
  ...makeRotationChain({ routed: true, buySol: 0.9, rotateSol: 0.5, sellSol: 0.35, tag: 'd2',
    startTs: DEFAULTS.startTs + 86400 * 5 }).txs,
  ...makeRotationChain({ routed: false, buySol: 1.5, sellSol: 0.6, tag: 'd3',
    startTs: DEFAULTS.startTs + 86400 * 8 }).txs,
  ...makeRotationChain({ routed: false, buySol: 0.8, sellSol: 1.9, tag: 'd4',
    startTs: DEFAULTS.startTs + 86400 * 11 }).txs,
]
txs.push(...rotationTxs)
txs.sort((a, b) => b.timestamp - a.timestamp)

const dry = analyze(txs, DEFAULTS.wallet)
const mints = dry.openBags.pricingMints
const DEMO_PRICES = {
  ok: true,
  source: 'synthetic (demo data)',
  skipped: 0,
  entries: Object.fromEntries(
    mints.map((m, i) => {
      // costSol per bag is openBagSize (1.3); qty is 5000. Spot prices are chosen to
      // produce a spread of outcomes rather than a uniform one.
      const shape = [
        { solPrice: 0.00048, liquiditySol: 900 },   // up ~85%, deep pool
        { solPrice: 0.00011, liquiditySol: 400 },   // down ~58%
        { solPrice: 0.00004, liquiditySol: 120 },   // down ~85%
        { solPrice: 0.00021, liquiditySol: 6 },     // marked 1.05 into 6 SOL — material impact
        { solPrice: 0.00002, liquiditySol: 30 },    // down ~92%
        { solPrice: 0.00039, liquiditySol: 1.2 },   // marked 1.95 into 1.2 SOL — exceeds depth
        null,                                       // no tradable pool at all
      ][i % 7]
      return shape ? [m, { ...shape, usdPrice: null, liquidityUsd: null, quoteIsSol: true, dex: 'raydium' }] : [m, null]
    }).filter(([, v]) => v),
  ),
}

const result = analyze(txs, DEFAULTS.wallet, { prices: DEMO_PRICES })
result.demo = true
result.wallet = 'DEMo7xW4Lk2pQhN9vRc3sT8uYbF6gJ1mAeZdK5nHqXyz'
// shorten the ledger for bundle size; the UI caps display anyway
result.trades = result.trades.slice(0, 24)

const banner = `// AUTO-GENERATED by scripts/gen-demo.mjs — do not edit by hand.
// Produced by running the real engine over a synthetic wallet, so the demo shape
// always matches live output. Regenerate with: node scripts/gen-demo.mjs
`
writeFileSync(
  new URL('../src/demo.js', import.meta.url),
  `${banner}export const DEMO_RESULT = ${JSON.stringify(result, null, 1)}\n`,
)

console.log('src/demo.js written')
console.log(`  archetype: ${result.archetype.primary.name} ${Math.round(result.archetype.primary.p * 100)}%`)
console.log(`  diagnosis: ${result.diagnosis.headline} (${result.diagnosis.edge} | ${result.diagnosis.process})`)
console.log(`  score: ${result.score.value} [${result.score.ci?.lo}-${result.score.ci?.hi}] ${result.score.grade}`)
console.log(`  trades: ${result.scorecard.closedTrades}, net ${result.scorecard.netPnlSol.toFixed(2)} SOL, tier ${result.confidence.label}`)
console.log(`  findings: +${result.strengths.length} strengths, -${result.leaks.length} leaks, ${result.counterfactuals.length} counterfactuals`)
const ob = result.openBags
console.log(`  open bags: ${ob.count} (${ob.basis}) — basis ${ob.totals.costSol.toFixed(2)} SOL, marked ${ob.totals.markSol?.toFixed(2) ?? '—'} SOL, unrealized ${ob.totals.unrealizedSol?.toFixed(2) ?? '—'} SOL`)
console.log(`             ${ob.totals.pricedCount}/${ob.totals.count} priced, ${ob.totals.materialImpactCount} with unrealistic marks, coverage ${(ob.totals.coverage * 100).toFixed(0)}%`)
const rr = result.sample.rotations
console.log(`  rotations: ${rr.total} total — ${rr.valued} valued, ${rr.basisRolled} basis-rolled, ${rr.ambiguous + rr.multiLeg + rr.noBasis} unattributed; ${rr.closedFromRotations} closed trades from rotations`)
console.log(`  position:  realized ${result.position.realizedSol.toFixed(2)} + unrealized ${result.position.unrealizedSol?.toFixed(2) ?? '—'} = ${result.position.totalSol?.toFixed(2) ?? '—'} SOL (if exited: ${result.position.totalRealizableSol?.toFixed(2) ?? '—'})`)
