// AUTO-GENERATED by scripts/gen-demo.mjs — do not edit by hand.
// Produced by running the real engine over a synthetic wallet, so the demo shape
// always matches live output. Regenerate with: node scripts/gen-demo.mjs
export const DEMO_RESULT = {
 "wallet": "DEMo7xW4Lk2pQhN9vRc3sT8uYbF6gJ1mAeZdK5nHqXyz",
 "engineVersion": "engine-v1",
 "referenceVersion": "prior-v0 (research-derived, unmeasured)",
 "cohort": {
  "wallets": 0,
  "basis": "prior",
  "version": "prior-v0 (research-derived, unmeasured)",
  "note": "No measured cohort supplied; percentiles read against research-derived priors."
 },
 "confidence": {
  "min": 80,
  "key": "substantive",
  "label": "Substantive",
  "blurb": "80+ closed trades. Rates are tight enough to act on.",
  "n": 133
 },
 "sample": {
  "txScanned": 275,
  "swapEvents": 269,
  "closedTrades": 133,
  "excluded": {
   "rotations": 0,
   "sellsWithoutBasis": 0,
   "nonSwapTx": 2
  },
  "rotations": {
   "total": 4,
   "valued": 2,
   "basisRolled": 2,
   "ambiguous": 0,
   "multiLeg": 0,
   "noBasis": 0,
   "closedFromRotations": 2
  },
  "firstTs": 1735689600,
  "lastTs": 1737667980,
  "spanDays": 22.60625
 },
 "diagnosis": {
  "edge": "negative",
  "process": "broken",
  "headline": "Compounding the wrong things",
  "reading": "Negative expectancy and multiple behavioral leaks reinforcing each other. This is the profile a behavioral system is built to trade against.",
  "provable": true,
  "counts": {
   "processLeaks": 4,
   "processStrengths": 2,
   "outcomeStrengths": 0,
   "outcomeLeaks": 1
  }
 },
 "scorecard": {
  "closedTrades": 133,
  "tokensTraded": 133,
  "winsLosses": [
   34,
   99
  ],
  "netPnlSol": -36.94330807000001,
  "netPnlCI": {
   "point": -36.94330807000001,
   "lo": -56.90808428742501,
   "hi": -18.274627139274997,
   "n": 133
  },
  "grossWinSol": 33.198728468999995,
  "grossLossSol": 70.142036539,
  "tollSol": 1.9361722370000043,
  "networkFeeSol": 0.040349999999999955,
  "interfaceTollSol": 1.8958222370000044,
  "tollRate": 0.008924807797786805,
  "selectionPnlSol": -35.00713583300001,
  "turnoverSol": 216.94273768899996,
  "basisSol": 210.3608376889999,
  "peakCapitalSol": 9.1819,
  "returnOnCapital": -4.023492748777486,
  "winRate": {
   "point": 0.2556390977443609,
   "lo": 0.189088826965417,
   "hi": 0.3359094191819532,
   "n": 133
  },
  "winRateShrunk": {
   "value": 0.27712418300653596,
   "sd": 0.03606689043584174,
   "weightOnData": 0.869281045751634,
   "priorMean": 0.42
  },
  "profitFactor": {
   "point": 0.473307165105493,
   "lo": 0.29255644046698387,
   "hi": 0.7084552673694404,
   "n": 133
  },
  "expectancy": {
   "point": -0.17561875335663693,
   "lo": -0.2627663605875071,
   "hi": -0.08524028332092504,
   "n": 133
  },
  "expectancyShrunk": {
   "value": -0.17449416917371463,
   "weightOnData": 0.9797804856266505,
   "priorMean": -0.12
  },
  "avgWinSol": 0.9764331902647058,
  "avgLossSol": 0.7085054195858587,
  "payoffRatio": 1.378159098395406,
  "tradeSharpe": -0.33320459612827985,
  "maxDrawdownSol": 38.20200566300001,
  "top3ShareOfGrossWin": 0.17924850614555024,
  "medianTradeRet": -0.42363583121654025,
  "bestTradeSol": 2.2133669339999997,
  "worstTradeSol": -1.8367619119999996,
  "tradesPerDay": 5.883328725463091,
  "spanDays": 22.60625,
  "equity": [
   {
    "ts": 1735712256,
    "cum": -0.302977277
   },
   {
    "ts": 1735732618,
    "cum": -0.449206875
   },
   {
    "ts": 1735750133,
    "cum": -1.832501264
   },
   {
    "ts": 1735751553,
    "cum": -1.0743047190000001
   },
   {
    "ts": 1735759307,
    "cum": -0.5353080010000002
   },
   {
    "ts": 1735774018,
    "cum": -0.8084663840000001
   },
   {
    "ts": 1735797264,
    "cum": -1.6274188290000005
   },
   {
    "ts": 1735814165,
    "cum": -2.4389468830000003
   },
   {
    "ts": 1735832418,
    "cum": -3.528052112
   },
   {
    "ts": 1735840537,
    "cum": -4.336139045
   },
   {
    "ts": 1735841539,
    "cum": -3.4444691320000005
   },
   {
    "ts": 1735865869,
    "cum": -3.9836379560000004
   },
   {
    "ts": 1735866000,
    "cum": -3.0836379560000005
   },
   {
    "ts": 1735869600,
    "cum": -3.7836379560000006
   },
   {
    "ts": 1735889430,
    "cum": -4.279405775000001
   },
   {
    "ts": 1735890778,
    "cum": -2.9214193930000008
   },
   {
    "ts": 1735925376,
    "cum": -3.5961180870000007
   },
   {
    "ts": 1735943314,
    "cum": -4.7936127420000005
   },
   {
    "ts": 1735944182,
    "cum": -2.9910220160000005
   },
   {
    "ts": 1735962477,
    "cum": -3.6876048210000008
   },
   {
    "ts": 1735974959,
    "cum": -5.104349838000001
   },
   {
    "ts": 1735996105,
    "cum": -5.892123287
   },
   {
    "ts": 1736016771,
    "cum": -6.187097946000001
   },
   {
    "ts": 1736032822,
    "cum": -6.484895704
   },
   {
    "ts": 1736033447,
    "cum": -6.254297136000001
   },
   {
    "ts": 1736041682,
    "cum": -5.841283082
   },
   {
    "ts": 1736069974,
    "cum": -6.609548664
   },
   {
    "ts": 1736082843,
    "cum": -6.6138598250000005
   },
   {
    "ts": 1736084059,
    "cum": -6.183035924
   },
   {
    "ts": 1736109370,
    "cum": -6.4413551490000005
   },
   {
    "ts": 1736116889,
    "cum": -6.244380636000001
   },
   {
    "ts": 1736125200,
    "cum": -6.644380636000001
   },
   {
    "ts": 1736128800,
    "cum": -6.794380636000001
   },
   {
    "ts": 1736148238,
    "cum": -7.208406183000001
   },
   {
    "ts": 1736166439,
    "cum": -7.815820747000001
   },
   {
    "ts": 1736167233,
    "cum": -6.374448649000001
   },
   {
    "ts": 1736196037,
    "cum": -6.866509591000002
   },
   {
    "ts": 1736216685,
    "cum": -7.837975873000001
   },
   {
    "ts": 1736237772,
    "cum": -8.758621659000001
   },
   {
    "ts": 1736238664,
    "cum": -7.513551353000001
   },
   {
    "ts": 1736267749,
    "cum": -8.321013675000001
   },
   {
    "ts": 1736279608,
    "cum": -8.811470680000001
   },
   {
    "ts": 1736280874,
    "cum": -6.598103746000001
   },
   {
    "ts": 1736314550,
    "cum": -6.885075493000001
   },
   {
    "ts": 1736333358,
    "cum": -7.313192671000001
   },
   {
    "ts": 1736351066,
    "cum": -7.9708890650000015
   },
   {
    "ts": 1736371035,
    "cum": -8.217812034000001
   },
   {
    "ts": 1736380177,
    "cum": -9.499716645000001
   },
   {
    "ts": 1736380780,
    "cum": -8.771030656
   },
   {
    "ts": 1736388000,
    "cum": -9.671030656000001
   },
   {
    "ts": 1736416278,
    "cum": -9.677542338
   },
   {
    "ts": 1736417397,
    "cum": -9.08829699
   },
   {
    "ts": 1736430345,
    "cum": -9.820374195
   },
   {
    "ts": 1736446288,
    "cum": -10.460566789
   },
   {
    "ts": 1736462321,
    "cum": -10.821051304
   },
   {
    "ts": 1736463232,
    "cum": -9.282671943999999
   },
   {
    "ts": 1736468757,
    "cum": -8.527638757999998
   },
   {
    "ts": 1736494142,
    "cum": -8.988892886999999
   },
   {
    "ts": 1736509541,
    "cum": -9.061160755999998
   },
   {
    "ts": 1736530511,
    "cum": -10.225734146999997
   },
   {
    "ts": 1736546938,
    "cum": -11.160417197999998
   },
   {
    "ts": 1736562631,
    "cum": -12.933893649999998
   },
   {
    "ts": 1736576886,
    "cum": -14.476013684999998
   },
   {
    "ts": 1736601811,
    "cum": -14.842492107999998
   },
   {
    "ts": 1736617147,
    "cum": -15.893221424999998
   },
   {
    "ts": 1736617892,
    "cum": -14.749646741
   },
   {
    "ts": 1736641494,
    "cum": -15.175241288999999
   },
   {
    "ts": 1736647200,
    "cum": -14.075241289
   },
   {
    "ts": 1736660128,
    "cum": -15.077506804999999
   },
   {
    "ts": 1736665519,
    "cum": -16.039573621
   },
   {
    "ts": 1736680725,
    "cum": -16.444372636
   },
   {
    "ts": 1736682318,
    "cum": -15.021040499000001
   },
   {
    "ts": 1736691383,
    "cum": -14.700559878000002
   },
   {
    "ts": 1736721458,
    "cum": -15.225535874000002
   },
   {
    "ts": 1736741151,
    "cum": -15.327450497000003
   },
   {
    "ts": 1736758372,
    "cum": -15.417198020000003
   },
   {
    "ts": 1736780230,
    "cum": -16.498236440000003
   },
   {
    "ts": 1736804606,
    "cum": -17.235082882000004
   },
   {
    "ts": 1736826075,
    "cum": -17.550564729000005
   },
   {
    "ts": 1736826964,
    "cum": -17.100038480000006
   },
   {
    "ts": 1736839623,
    "cum": -17.707189217000007
   },
   {
    "ts": 1736851794,
    "cum": -18.712033077000008
   },
   {
    "ts": 1736876142,
    "cum": -20.548794989000008
   },
   {
    "ts": 1736900531,
    "cum": -21.74020858300001
   },
   {
    "ts": 1736926479,
    "cum": -22.23682914300001
   },
   {
    "ts": 1736952001,
    "cum": -22.799530382000007
   },
   {
    "ts": 1736953160,
    "cum": -20.916963088000006
   },
   {
    "ts": 1736977382,
    "cum": -21.420684374000007
   },
   {
    "ts": 1736992765,
    "cum": -21.870834436000006
   },
   {
    "ts": 1736993723,
    "cum": -21.111184539000007
   },
   {
    "ts": 1737021781,
    "cum": -21.224436643000008
   },
   {
    "ts": 1737035174,
    "cum": -22.289599085000006
   },
   {
    "ts": 1737045981,
    "cum": -23.519834723000006
   },
   {
    "ts": 1737062804,
    "cum": -24.321902519000005
   },
   {
    "ts": 1737064209,
    "cum": -23.421767562000007
   },
   {
    "ts": 1737088025,
    "cum": -23.879492448000008
   },
   {
    "ts": 1737097515,
    "cum": -24.07406191500001
   },
   {
    "ts": 1737119818,
    "cum": -24.87720824300001
   },
   {
    "ts": 1737126614,
    "cum": -25.688580717000008
   },
   {
    "ts": 1737135798,
    "cum": -26.320032898000008
   },
   {
    "ts": 1737152779,
    "cum": -27.461749687000008
   },
   {
    "ts": 1737166378,
    "cum": -28.47927316100001
   },
   {
    "ts": 1737194595,
    "cum": -29.573825835000008
   },
   {
    "ts": 1737222834,
    "cum": -30.64244912200001
   },
   {
    "ts": 1737240901,
    "cum": -32.11999376800001
   },
   {
    "ts": 1737242497,
    "cum": -31.243727386000007
   },
   {
    "ts": 1737257549,
    "cum": -31.688966591000007
   },
   {
    "ts": 1737283791,
    "cum": -32.47229523200001
   },
   {
    "ts": 1737305711,
    "cum": -33.181697277000005
   },
   {
    "ts": 1737306781,
    "cum": -32.35919212500001
   },
   {
    "ts": 1737332070,
    "cum": -33.14689020000001
   },
   {
    "ts": 1737347199,
    "cum": -34.16785450700001
   },
   {
    "ts": 1737365092,
    "cum": -35.125347268000006
   },
   {
    "ts": 1737377736,
    "cum": -36.086315592000005
   },
   {
    "ts": 1737378643,
    "cum": -34.231427336
   },
   {
    "ts": 1737387284,
    "cum": -33.636235307
   },
   {
    "ts": 1737400218,
    "cum": -33.653071238
   },
   {
    "ts": 1737401465,
    "cum": -32.495140932000005
   },
   {
    "ts": 1737418709,
    "cum": -32.62676964600001
   },
   {
    "ts": 1737447264,
    "cum": -33.410262081000006
   },
   {
    "ts": 1737463212,
    "cum": -34.97275995900001
   },
   {
    "ts": 1737488216,
    "cum": -35.53014917200001
   },
   {
    "ts": 1737489562,
    "cum": -34.41323842800001
   },
   {
    "ts": 1737514231,
    "cum": -34.79928921300001
   },
   {
    "ts": 1737530450,
    "cum": -35.33330224800001
   },
   {
    "ts": 1737531907,
    "cum": -34.51175951000001
   },
   {
    "ts": 1737536891,
    "cum": -34.13221189800001
   },
   {
    "ts": 1737551354,
    "cum": -34.65884365800001
   },
   {
    "ts": 1737576141,
    "cum": -36.10816166200001
   },
   {
    "ts": 1737601110,
    "cum": -36.63449467000001
   },
   {
    "ts": 1737620374,
    "cum": -37.585071430000006
   },
   {
    "ts": 1737641578,
    "cum": -38.504982940000005
   },
   {
    "ts": 1737642780,
    "cum": -36.94330807000001
   }
  ]
 },
 "behavior": {
  "medianHoldWinMin": 11.391666666666666,
  "medianHoldLossMin": 295.46666666666664,
  "disposition": {
   "point": 25.937088514996343,
   "ci": {
    "point": 25.937088514996343,
    "lo": 21.586112339672713,
    "hi": 30.962233169129718,
    "n": 133
   },
   "pctWorst": 0.98,
   "nWin": 34,
   "nLoss": 99,
   "verdict": [
    "critical",
    "chronic bagholding"
   ]
  },
  "panic": {
   "point": 0,
   "lo": 3.469446951953614e-18,
   "hi": 0.03735453357396229,
   "n": 99,
   "pctWorst": 0.1,
   "verdict": [
    "good",
    "composed exits"
   ]
  },
  "revenge": {
   "point": 13.908235294117647,
   "medGapAfterLossMin": 7.083333333333333,
   "medGapAfterWinMin": 98.51666666666667,
   "nLoss": 99,
   "nWin": 34,
   "pctWorst": 0.97,
   "verdict": [
    "critical",
    "severe tilt"
   ]
  },
  "sizing": {
   "cv": 0.5488070005989877,
   "escalation": 1.8302351463690871,
   "nPostLoss": 96,
   "nBaseline": 42,
   "medianBuySol": 1.432382161,
   "nBuys": 138,
   "pctWorst": 0.39067250049915636,
   "verdict": [
    "warning",
    "mostly consistent"
   ]
  },
  "toll": {
   "rate": 0.008924807797786805,
   "pctWorst": 0.2846802924170052,
   "verdict": [
    "good",
    "lean execution"
   ]
  },
  "bags": {
   "count": 7,
   "costSol": 9.1819
  },
  "trend": {
   "first": -0.14660502390994826,
   "second": -0.20221502709429032,
   "delta": -0.05561000318434206
  },
  "percentiles": {
   "disposition": 0.98,
   "panic": 0.1,
   "revenge": 0.97,
   "sizing": 0.39067250049915636,
   "expectancy": 0.5344697613128745,
   "profitFactor": 0.7333520249246479,
   "tollRate": 0.2846802924170052
  }
 },
 "counterfactuals": [
  {
   "key": "no_toll",
   "label": "If the house took nothing",
   "deltaSol": 1.9361722370000043,
   "note": "Visible toll paid across 271 legs: network fees plus interface/tip outflows. Lower bound — fees routed pool-to-interface never touch your wallet and cannot be counted.",
   "hindsight": false
  },
  {
   "key": "no_revenge",
   "label": "If you'd waited an hour after each loss",
   "deltaSol": 27.959020094000007,
   "note": "97 of 133 trades were entered within 60 minutes of closing a loser. Together they lost 27.96 SOL.",
   "hindsight": false,
   "count": 97
  },
  {
   "key": "flat_size",
   "label": "If every position were the same size",
   "deltaSol": 5.394019476601759,
   "note": "Sizing every trade at 1.43 SOL would have returned 5.39 SOL more than you actually made. Your conviction sizing worked against you: the bigger bets were the worse ones.",
   "hindsight": false
  },
  {
   "key": "symmetric_patience",
   "label": "Capital tied up in losers past your winner-hold time",
   "deltaSol": null,
   "exposure": {
    "solDays": 30.45473723336736,
    "count": 99
   },
   "note": "You give winners a median 11 min. 99 losing positions were held beyond that, costing 30.5 SOL-days of tied-up capital (position size multiplied by the extra time held, summed). Not a loss and not a peak exposure — it is capital that could not be redeployed. No PnL claim: the counterfactual price path is unknowable from your ledger alone.",
   "hindsight": false
  },
  {
   "key": "concentration",
   "label": "Share of all profit from your best 3 trades",
   "pct": 0.17924850614555024,
   "deltaSol": null,
   "note": "18% of gross profit from your best 3 — reasonably distributed rather than one lucky hit carrying the book.",
   "hindsight": true
  }
 ],
 "archetype": {
  "unread": false,
  "primary": {
   "key": "bagholder",
   "name": "The Bagholder",
   "tagline": "You call it conviction. The ledger calls it denial.",
   "desc": "Winners sold fast, losers held indefinitely. The disposition effect, measured on your own exits.",
   "score": 0.9259635436646649,
   "terms": [
    [
     1,
     1.5
    ],
    [
     1,
     0.8
    ],
    [
     0.5853958445221231,
     0.5
    ]
   ],
   "p": 0.517337241193398
  },
  "mixture": [
   {
    "key": "bagholder",
    "name": "The Bagholder",
    "tagline": "You call it conviction. The ledger calls it denial.",
    "desc": "Winners sold fast, losers held indefinitely. The disposition effect, measured on your own exits.",
    "score": 0.9259635436646649,
    "terms": [
     [
      1,
      1.5
     ],
     [
      1,
      0.8
     ],
     [
      0.5853958445221231,
      0.5
     ]
    ],
    "p": 0.517337241193398
   },
   {
    "key": "tilted",
    "name": "The Tilted",
    "tagline": "Every loss is a countdown to a bigger buy.",
    "desc": "Re-enters faster after losses than after wins, and sizes up to recover. Martingale with extra steps.",
    "score": 0.8676016120546217,
    "terms": [
     [
      1,
      1.5
     ],
     [
      0.9151175731845436,
      1.1
     ],
     [
      0.36587133373265845,
      0.5
     ]
    ],
    "p": 0.3702283951337935
   },
   {
    "key": "exit_liquidity",
    "name": "Prime Exit Liquidity",
    "tagline": "The machine has a folder on you.",
    "desc": "High turnover, low hit rate, negative expectancy. This is the flow other systems are built to harvest.",
    "score": 0.5742576923521356,
    "terms": [
     [
      0.5017678667332484,
      1.4
     ],
     [
      0.3913354815610455,
      1
     ],
     [
      0.9805547875771818,
      0.7
     ]
    ],
    "p": 0.06888581059828022
   }
  ],
  "temperature": 0.17443609022556392,
  "hedged": false
 },
 "strengths": [
  {
   "kind": "process",
   "title": "You do not flinch",
   "detail": "At most 4% of losing exits happened inside 10 minutes, interval included. You are not selling on reflex.",
   "evidence": "0% of 99 losing exits, 95% CI 0-4%"
  },
  {
   "kind": "process",
   "title": "Lean execution",
   "detail": "Visible toll is 0.89% of turnover. You are not donating to interfaces.",
   "evidence": "1.936 SOL toll on 216.9 SOL turnover"
  }
 ],
 "leaks": [
  {
   "kind": "process",
   "title": "Disposition effect",
   "detail": "Losers are held 25.9x longer than winners. Odean measured this in 1998; your ledger repeats it.",
   "evidence": "median hold: winners 11m, losers 295m, ratio 95% CI 21.6-31.0"
  },
  {
   "kind": "process",
   "title": "Tilt after losses",
   "detail": "You re-enter 13.9x faster after a loss than after a win. That is the tilt signature, and it is the single most modellable thing a wallet can do.",
   "evidence": "median gap after loss 7m vs after win 99m (99 losses, 34 wins)"
  },
  {
   "kind": "process",
   "title": "Sizing up to recover",
   "detail": "Buys inside an hour of a losing exit average 1.8x the size of your other buys. Martingale sizing turns a bad session into a bad month.",
   "evidence": "96 post-loss buys vs 42 baseline buys"
  },
  {
   "kind": "outcome",
   "title": "Negative expectancy",
   "detail": "Every SOL of basis you deploy returns -0.18 SOL, and the entire interval sits below zero. Trading more often multiplies this; it does not fix it.",
   "evidence": "133 trades, 95% CI -0.26 to -0.09"
  },
  {
   "kind": "process",
   "title": "Open bag pile",
   "detail": "7 positions still open with 9.18 SOL of cost basis. Whether that is a loss depends on the marks listed below; none of it sits in any realized figure above.",
   "evidence": "7 open positions, excluded from every realized metric"
  }
 ],
 "score": {
  "value": 28,
  "ci": {
   "lo": 13,
   "hi": 41
  },
  "grade": "Readable",
  "components": {
   "leak": 0.35123750671327386,
   "readability": 0.6726789499101518,
   "cadence": 0.5883328725463091,
   "amplifier": 0.7833643113787688
  },
  "formula": "score = 100 x leak x [0.4 + 0.6 x (0.6 x readability + 0.4 x cadence)]",
  "why": "A stated formula over three measured components, not a fitted model. Readability and cadence only amplify an existing leak — they never create one."
 },
 "openBags": {
  "count": 7,
  "costSol": 9.1819,
  "basis": "partial",
  "partial": true,
  "totals": {
   "count": 7,
   "pricedCount": 6,
   "unpricedCount": 1,
   "costSol": 9.1819,
   "pricedCostSol": 7.8702000000000005,
   "unpricedCostSol": 1.3117,
   "coverage": 0.8571428571428571,
   "markSol": 6.25,
   "realizableSol": 4.878670969210479,
   "unrealizedSol": -1.6202000000000005,
   "unrealizedRealizableSol": -2.991529030789522,
   "materialImpactCount": 2
  },
  "items": [
   {
    "mint": "BAG0",
    "qty": 5000,
    "costSol": 1.3117,
    "firstTs": 1737646380,
    "priced": true,
    "solPrice": 0.00048,
    "markSol": 2.4,
    "realizableSol": 2.393617021276596,
    "unrealizedSol": 1.0882999999999998,
    "impactShare": 0.0026666666666666666,
    "liquiditySol": 900,
    "dex": "raydium",
    "flags": [],
    "unrealizedRealizableSol": 1.0819170212765958,
    "liquidityUsd": null
   },
   {
    "mint": "BAG1",
    "qty": 5000,
    "costSol": 1.3117,
    "firstTs": 1737649980,
    "priced": true,
    "solPrice": 0.00011,
    "markSol": 0.55,
    "realizableSol": 0.5492447884159282,
    "unrealizedSol": -0.7617,
    "impactShare": 0.0013750000000000001,
    "liquiditySol": 400,
    "dex": "raydium",
    "flags": [],
    "unrealizedRealizableSol": -0.7624552115840719,
    "liquidityUsd": null
   },
   {
    "mint": "BAG2",
    "qty": 5000,
    "costSol": 1.3117,
    "firstTs": 1737653580,
    "priced": true,
    "solPrice": 0.00004,
    "markSol": 0.2,
    "realizableSol": 0.19966722129783696,
    "unrealizedSol": -1.1117000000000001,
    "impactShare": 0.0016666666666666668,
    "liquiditySol": 120,
    "dex": "raydium",
    "flags": [],
    "unrealizedRealizableSol": -1.112032778702163,
    "liquidityUsd": null
   },
   {
    "mint": "BAG3",
    "qty": 5000,
    "costSol": 1.3117,
    "firstTs": 1737657180,
    "priced": true,
    "solPrice": 0.00021,
    "markSol": 1.05,
    "realizableSol": 0.8936170212765957,
    "unrealizedSol": -0.26170000000000004,
    "impactShare": 0.17500000000000002,
    "liquiditySol": 6,
    "dex": "raydium",
    "flags": [
     "material-impact"
    ],
    "unrealizedRealizableSol": -0.4180829787234044,
    "liquidityUsd": null
   },
   {
    "mint": "BAG4",
    "qty": 5000,
    "costSol": 1.3117,
    "firstTs": 1737660780,
    "priced": true,
    "solPrice": 0.00002,
    "markSol": 0.1,
    "realizableSol": 0.09966777408637874,
    "unrealizedSol": -1.2117,
    "impactShare": 0.0033333333333333335,
    "liquiditySol": 30,
    "dex": "raydium",
    "flags": [],
    "unrealizedRealizableSol": -1.2120322259136214,
    "liquidityUsd": null
   },
   {
    "mint": "BAG5",
    "qty": 5000,
    "costSol": 1.3117,
    "firstTs": 1737664380,
    "priced": true,
    "solPrice": 0.00039,
    "markSol": 1.95,
    "realizableSol": 0.7428571428571429,
    "unrealizedSol": 0.6382999999999999,
    "impactShare": 1.625,
    "liquiditySol": 1.2,
    "dex": "raydium",
    "flags": [
     "exceeds-pool-depth"
    ],
    "unrealizedRealizableSol": -0.5688428571428572,
    "liquidityUsd": null
   },
   {
    "mint": "BAG6",
    "qty": 5000,
    "costSol": 1.3117,
    "firstTs": 1737667980,
    "priced": false,
    "solPrice": null,
    "markSol": null,
    "realizableSol": null,
    "unrealizedSol": null,
    "impactShare": null,
    "liquiditySol": null,
    "dex": null,
    "flags": [
     "unpriced"
    ]
   }
  ],
  "pricingMints": [
   "BAG0",
   "BAG1",
   "BAG2",
   "BAG3",
   "BAG4",
   "BAG5",
   "BAG6"
  ],
  "source": "synthetic (demo data)",
  "note": null,
  "skipped": 0,
  "excludedFromMetrics": "Marks are disclosure only. No behavioral metric, finding, diagnosis or score reads a price."
 },
 "position": {
  "realizedSol": -36.94330807000001,
  "unrealizedSol": -1.6202000000000005,
  "unrealizedRealizableSol": -2.991529030789522,
  "totalSol": -38.56350807000001,
  "totalRealizableSol": -39.93483710078953,
  "basis": "partial",
  "coverage": 0.8571428571428571,
  "caveat": "Combined figure covers only the 86% of open cost basis that could be marked; 1 position remains unpriced."
 },
 "trades": [
  {
   "mint": "MINT127",
   "pnl": 1.56167487,
   "cost": 2.360654607,
   "proceeds": 3.922329477,
   "ret": 0.6615431437403838,
   "holdMin": 11.233333333333333,
   "entryTs": 1737642106,
   "exitTs": 1737642780,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT126",
   "pnl": -0.9199115100000004,
   "cost": 2.2583108170000004,
   "proceeds": 1.338399307,
   "ret": -0.4073449514013465,
   "holdMin": 346.23333333333335,
   "entryTs": 1737620804,
   "exitTs": 1737641578,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT125",
   "pnl": -0.95057676,
   "cost": 1.625611911,
   "proceeds": 0.675035151,
   "ret": -0.5847501199811276,
   "holdMin": 314.26666666666665,
   "entryTs": 1737601518,
   "exitTs": 1737620374,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT124",
   "pnl": -0.526333008,
   "cost": 1.158996146,
   "proceeds": 0.632663138,
   "ret": -0.454128350483747,
   "holdMin": 407.8666666666667,
   "entryTs": 1737576638,
   "exitTs": 1737601110,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT123",
   "pnl": -1.4493180040000002,
   "cost": 3.959325348,
   "proceeds": 2.510007344,
   "ret": -0.36605175796732736,
   "holdMin": 406.21666666666664,
   "entryTs": 1737551768,
   "exitTs": 1737576141,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT122",
   "pnl": -0.5266317599999999,
   "cost": 1.0943595529999999,
   "proceeds": 0.567727793,
   "ret": -0.4812237061908299,
   "holdMin": 140.68333333333334,
   "entryTs": 1737542913,
   "exitTs": 1737551354,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT121",
   "pnl": 0.379547612,
   "cost": 0.659333324,
   "proceeds": 1.038880936,
   "ret": 0.575653615833317,
   "holdMin": 8.7,
   "entryTs": 1737536369,
   "exitTs": 1737536891,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT120",
   "pnl": 0.8215427380000002,
   "cost": 1.5148362149999999,
   "proceeds": 2.336378953,
   "ret": 0.5423310651442277,
   "holdMin": 16.683333333333334,
   "entryTs": 1737530906,
   "exitTs": 1737531907,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT119",
   "pnl": -0.534013035,
   "cost": 1.174560699,
   "proceeds": 0.640547664,
   "ret": -0.45464915985580745,
   "holdMin": 262.9166666666667,
   "entryTs": 1737514675,
   "exitTs": 1737530450,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT118",
   "pnl": -0.386050785,
   "cost": 0.954907347,
   "proceeds": 0.568856562,
   "ret": -0.40428088255142514,
   "holdMin": 329.28333333333336,
   "entryTs": 1737494474,
   "exitTs": 1737514231,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT117",
   "pnl": 1.116910744,
   "cost": 1.810108845,
   "proceeds": 2.927019589,
   "ret": 0.6170406531547554,
   "holdMin": 15.4,
   "entryTs": 1737488638,
   "exitTs": 1737489562,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT116",
   "pnl": -0.5573892130000001,
   "cost": 1.255675311,
   "proceeds": 0.698286098,
   "ret": -0.44389597224469124,
   "holdMin": 412.18333333333334,
   "entryTs": 1737463485,
   "exitTs": 1737488216,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT115",
   "pnl": -1.562497878,
   "cost": 2.7865004,
   "proceeds": 1.224002522,
   "ret": -0.5607384366426074,
   "holdMin": 257.8333333333333,
   "entryTs": 1737447742,
   "exitTs": 1737463212,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT114",
   "pnl": -0.783492435,
   "cost": 1.676738555,
   "proceeds": 0.89324612,
   "ret": -0.46727167611410947,
   "holdMin": 467.21666666666664,
   "entryTs": 1737419231,
   "exitTs": 1737447264,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT113",
   "pnl": -0.131628714,
   "cost": 0.234766633,
   "proceeds": 0.103137919,
   "ret": -0.5606789700817493,
   "holdMin": 193.93333333333334,
   "entryTs": 1737407073,
   "exitTs": 1737418709,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT112",
   "pnl": 1.1579303060000001,
   "cost": 1.74926326,
   "proceeds": 2.907193566,
   "ret": 0.6619531390603837,
   "holdMin": 12.216666666666667,
   "entryTs": 1737400732,
   "exitTs": 1737401465,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT111",
   "pnl": -0.016835931000000002,
   "cost": 0.039625113000000003,
   "proceeds": 0.022789182,
   "ret": -0.42488032778606843,
   "holdMin": 152.71666666666667,
   "entryTs": 1737391055,
   "exitTs": 1737400218,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT110",
   "pnl": 0.5951920290000001,
   "cost": 0.770424448,
   "proceeds": 1.365616477,
   "ret": 0.772550806954662,
   "holdMin": 13.65,
   "entryTs": 1737386465,
   "exitTs": 1737387284,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT109",
   "pnl": 1.8548882560000002,
   "cost": 2.676067952,
   "proceeds": 4.530956208,
   "ret": 0.6931394453618869,
   "holdMin": 8.433333333333334,
   "entryTs": 1737378137,
   "exitTs": 1737378643,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT108",
   "pnl": -0.9609683240000001,
   "cost": 1.82106136,
   "proceeds": 0.860093036,
   "ret": -0.5276968393860161,
   "holdMin": 204.66666666666666,
   "entryTs": 1737365456,
   "exitTs": 1737377736,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT107",
   "pnl": -0.9574927610000001,
   "cost": 2.2050807310000002,
   "proceeds": 1.24758797,
   "ret": -0.43422118180942015,
   "holdMin": 289.9,
   "entryTs": 1737347698,
   "exitTs": 1737365092,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT106",
   "pnl": -1.0209643069999998,
   "cost": 2.171438936,
   "proceeds": 1.150474629,
   "ret": -0.4701786866181531,
   "holdMin": 246.38333333333333,
   "entryTs": 1737332416,
   "exitTs": 1737347199,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT105",
   "pnl": -0.7876980750000002,
   "cost": 1.5756132900000002,
   "proceeds": 0.787915215,
   "ret": -0.4999310934982023,
   "holdMin": 349.06666666666666,
   "entryTs": 1737311126,
   "exitTs": 1737332070,
   "partial": false,
   "via": "sol"
  },
  {
   "mint": "MINT104",
   "pnl": 0.8225051519999997,
   "cost": 2.723331845,
   "proceeds": 3.545836997,
   "ret": 0.3020216407009333,
   "holdMin": 12.983333333333333,
   "entryTs": 1737306002,
   "exitTs": 1737306781,
   "partial": false,
   "via": "sol"
  }
 ],
 "assumptions": [
  "Reference cohort: prior-v0 (research-derived, unmeasured). Percentiles compare you to research-derived priors, not to measured Mirror traffic. They are replaced with measured quantiles, per quantile, as scan volume accrues.",
  "Win-rate shrinkage prior: mean 0.42 with strength 20 pseudo-trades. Expectancy prior mean -0.12.",
  "Toll is a visible lower bound: fees routed from pool to interface never enter your wallet and cannot be attributed.",
  "Trade Sharpe is per-trade, not annualized. Memecoin holding periods are too uneven for calendar annualization to mean anything.",
  "Counterfactuals marked \"hindsight\" use outcome knowledge and overstate what was achievable in real time."
 ],
 "limits": [
  "4 token-to-token rotations: 2 valued at the SOL the router actually moved through the wallet, 2 carried their cost basis into the new position with no PnL claimed (nothing was realized in SOL), 0 left unattributed.",
  "Every behavioral metric is realized-only. Open positions are marked at spot for disclosure and feed nothing else. A mark assumes the deepest pool found, no swap fees, no routing, and nobody else selling — the realizable figure beside it is the honest bound.",
  "Sells of tokens acquired before the scan window have unknown basis and are excluded.",
  "Scan window: last 275 transactions."
 ],
 "demo": true
}
